// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGenrePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddGenrePrompt'](arg1, arg2, arg3);
}

export function AddGlossaryEntry(arg1, arg2) {
  return window['go']['main']['App']['AddGlossaryEntry'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetCacheSize() {
  return window['go']['main']['App']['GetCacheSize']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGenreList() {
  return window['go']['main']['App']['GetGenreList']();
}

export function GetGenrePrompt(arg1) {
  return window['go']['main']['App']['GetGenrePrompt'](arg1);
}

export function GetGlossary(arg1) {
  return window['go']['main']['App']['GetGlossary'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListGlossaries() {
  return window['go']['main']['App']['ListGlossaries']();
}

export function ProcessDroppedFiles(arg1) {
  return window['go']['main']['App']['ProcessDroppedFiles'](arg1);
}

export function RemoveGenrePrompt(arg1) {
  return window['go']['main']['App']['RemoveGenrePrompt'](arg1);
}

export function RemoveGlossaryEntry(arg1, arg2) {
  return window['go']['main']['App']['RemoveGlossaryEntry'](arg1, arg2);
}

export function SaveGlossary(arg1, arg2) {
  return window['go']['main']['App']['SaveGlossary'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function TranslateFile(arg1, arg2) {
  return window['go']['main']['App']['TranslateFile'](arg1, arg2);
}

export function TranslateFiles(arg1, arg2) {
  return window['go']['main']['App']['TranslateFiles'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateGenrePrompt(arg1, arg2) {
  return window['go']['main']['App']['UpdateGenrePrompt'](arg1, arg2);
}
