// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddGenrePrompt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddGlossaryEntry(arg1:string,arg2:models.GlossaryEntry):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function ClearCache():Promise<void>;

export function GetCacheInfo():Promise<main.CacheInfo>;

export function GetCacheSize():Promise<number>;

export function GetConfig():Promise<models.AppConfig>;

export function GetGenreList():Promise<Array<models.GenrePrompt>>;

export function GetGenrePrompt(arg1:string):Promise<models.GenrePrompt>;

export function GetGlossary(arg1:string):Promise<models.Glossary>;

export function GetProviders():Promise<Record<string, models.APIProvider>>;

export function GetTasks():Promise<Array<models.TranslationTask>>;

export function ListDirectory(arg1:string):Promise<Array<models.FileInfo>>;

export function ListGlossaries():Promise<Array<string>>;

export function ProcessDroppedFiles(arg1:Array<main.DroppedFile>):Promise<string>;

export function RemoveGenrePrompt(arg1:string):Promise<void>;

export function RemoveGlossaryEntry(arg1:string,arg2:string):Promise<void>;

export function SaveGlossary(arg1:string,arg2:models.Glossary):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function StopAll():Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<models.TestConnectionResult>;

export function TranslateFile(arg1:string,arg2:string):Promise<void>;

export function TranslateFiles(arg1:Array<string>,arg2:string):Promise<void>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;

export function UpdateGenrePrompt(arg1:string,arg2:string):Promise<void>;
